repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-ast
      - id: check-json
        exclude: ^frontend/tsconfig.*\.json
      - id: pretty-format-json
        exclude: ^frontend/tsconfig.*\.json
        args:
          - --autofix
          - --no-sort-keys
      - id: sort-simple-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-toml
