x-postgres-env: &postgres-env
  POSTGRES_USER: ${POSTGRES_USER:-divaldi}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
  POSTGRES_DB: ${POSTGRES_DB:-divaldi}
  POSTGRES_HOST: db

services:
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${BACKEND_URL:-http://localhost:3000}
    ports:
      - ${FRONTEND_PORT:-8080}:80
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-3000}
    restart: unless-stopped
    depends_on:
      - backend
    mem_limit: 1G

  backend:
    build: ./backend
    environment:
      <<: *postgres-env
      DEBUG: ${DEBUG:?}
      BACKEND_URL: ${BACKEND_URL:-http://localhost:3000}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8080}
    ports:
      - ${BACKEND_PORT:-3000}:3000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    mem_limit: 1G

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      <<: *postgres-env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-divaldi} -d ${POSTGRES_DB:-divaldi}",
        ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    shm_size: '512mb'
    mem_limit: 2G

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    mem_limit: 2G

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:?}
      RABBITMQ_DEFAULT_VHOST: taskiq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    mem_limit: 2G

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
