[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "yel-gar"}
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli] (>=0.141.1,<0.142.0)",
    "alembic (>=1.19.2,<2.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "structlog (>=26.1.0,<27.0.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "argon2-cffi (>=25.1.0,<26.0.0)",
    "starlette (>=1.6.0,<2.0.0)",
    "pydantic (>=2.13.5,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "ruff (>=0.16.6,<0.17.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]
