apiVersion: v1
metadata:
  name: postgres-init
kind: ConfigMap
data:
  01-taskiq-dashboard.sql: "CREATE DATABASE taskiq_dashboard;\r\n"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: divaldi
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: divaldi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "divaldi", "-d", "divaldi"]
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "divaldi", "-d", "divaldi"]
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "divaldi", "-d", "divaldi"]
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
