"""add chatmessage index

Revision ID: 0b048262d2ea
Revises: 4022148410b9
Create Date: 2026-09-13 00:24:30.765635

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b048262d2ea"
down_revision: str | Sequence[str] | None = "4022148410b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_chat_messages_session_id_timestamp_id",
        "chat_messages",
        ["chat_session_id", sa.literal_column("timestamp DESC"), "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_messages_session_id_timestamp_id", table_name="chat_messages")
    # ### end Alembic commands ###
