"""add chat messages

Revision ID: 1399fae31539
Revises: a80182150e6e
Create Date: 2026-09-10 12:28:15.532867

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1399fae31539"
down_revision: str | Sequence[str] | None = "a80182150e6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_results",
        sa.Column("message_session", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("ERROR", "SUCCESS", name="generationresulttype"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("message_session"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message_session", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("USER", "ASSISTANT", "SYSTEM", name="userrole"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_message_session"), "chat_messages", ["message_session"], unique=False)
    op.add_column("users", sa.Column("uuid", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False))
    op.create_unique_constraint("users_uuid_unique", "users", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_uuid_unique", "users", type_="unique")
    op.drop_column("users", "uuid")
    op.drop_index(op.f("ix_chat_messages_message_session"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_table("generation_results")

    sa.Enum(
        "USER",
        "ASSISTANT",
        "SYSTEM",
        name="userrole",
    ).drop(op.get_bind())

    sa.Enum(
        "ERROR",
        "SUCCESS",
        name="generationresulttype",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
