"""add configurable production rates to settings

Revision ID: 3d2adfe8c250
Revises: 697a55310c2d
Create Date: 2026-10-09 15:52:54.769783

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d2adfe8c250"
down_revision: str | Sequence[str] | None = "697a55310c2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "parameters")
    # ### end Alembic commands ###
