"""chat message add files str

Revision ID: 4022148410b9
Revises: f542203c47ed
Create Date: 2026-09-12 23:50:11.399284

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4022148410b9"
down_revision: str | Sequence[str] | None = "f542203c47ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_messages", sa.Column("files_str", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "files_str")
    # ### end Alembic commands ###
