"""add singleton settings table for the prompt extension

Revision ID: 697a55310c2d
Revises: 86f5aec9dae7
Create Date: 2026-10-09 15:21:56.266840

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "697a55310c2d"
down_revision: str | Sequence[str] | None = "86f5aec9dae7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("settings",
    sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
    sa.Column("prompt_extension", sa.Text(), nullable=False),
    sa.Column("last_update_by", sa.Integer(), nullable=True),
    sa.Column("last_update_at", sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("id = 1", name="ck_settings_singleton"),
    sa.ForeignKeyConstraint(["last_update_by"], ["users.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
