"""add attachments

Revision ID: f542203c47ed
Revises: 1399fae31539
Create Date: 2026-09-12 22:11:57.439628

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f542203c47ed"
down_revision: str | Sequence[str] | None = "1399fae31539"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("chat_message_id", sa.Integer(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ready", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["chat_message_id"], ["chat_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attachments_session_id"), "attachments", ["session_id"], unique=False)
    op.create_table(
        "processing_result_uploadables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("sber_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["attachment_id"], ["attachments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processing_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["attachment_id"], ["attachments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attachment_id"),
    )
    op.add_column("chat_messages", sa.Column("chat_session_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_chat_messages_message_session"), table_name="chat_messages")
    op.create_index(op.f("ix_chat_messages_chat_session_id"), "chat_messages", ["chat_session_id"], unique=False)
    op.drop_constraint(op.f("chat_messages_user_id_fkey"), "chat_messages", type_="foreignkey")
    op.create_foreign_key(
        "fk_chat_messages_chat_sessions",
        "chat_messages",
        "chat_sessions",
        ["chat_session_id"],
        ["session_id"],
        ondelete="CASCADE",
    )
    op.drop_column("chat_messages", "user_id")
    op.drop_column("chat_messages", "message_session")
    op.add_column("generation_results", sa.Column("chat_session_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "fk_generation_results_chat_sessions",
        "generation_results",
        "chat_sessions",
        ["chat_session_id"],
        ["session_id"],
        ondelete="CASCADE",
    )
    op.drop_column("generation_results", "message_session")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generation_results", sa.Column("message_session", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint("fk_generation_results_chat_sessions", "generation_results", type_="foreignkey")
    op.drop_column("generation_results", "chat_session_id")
    op.add_column("chat_messages", sa.Column("message_session", sa.UUID(), autoincrement=False, nullable=False))
    op.add_column("chat_messages", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("fk_chat_messages_chat_sessions", "chat_messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("chat_messages_user_id_fkey"), "chat_messages", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(op.f("ix_chat_messages_chat_session_id"), table_name="chat_messages")
    op.create_index(op.f("ix_chat_messages_message_session"), "chat_messages", ["message_session"], unique=False)
    op.drop_column("chat_messages", "chat_session_id")
    op.drop_table("processing_results")
    op.drop_table("processing_result_uploadables")
    op.drop_index(op.f("ix_attachments_session_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_table("chat_sessions")
    # ### end Alembic commands ###
